### ISSUE TITLE
Document features of 1.1

### ISSUE THREAD

**Issue by juzraai** [juzraai/cli-ask#11]
- [ ] #9 converter selection (README, exception class)
- [ ]  #10 long/multiline labels (AlignedText)
- [ ]  #7 recursive asking (PreparedField, AskFor, README)
